/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_henrywarhurst_facerecog_FisherSvmJava */

#ifndef _Included_com_henrywarhurst_facerecog_FisherSvmJava
#define _Included_com_henrywarhurst_facerecog_FisherSvmJava
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_henrywarhurst_facerecog_FisherSvmJava
 * Method:    nativeCreateObject
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_henrywarhurst_facerecog_FisherSvmJava_nativeCreateObject
  (JNIEnv *, jclass);

/*
 * Class:     com_henrywarhurst_facerecog_FisherSvmJava
 * Method:    nativeDestroyObject
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_henrywarhurst_facerecog_FisherSvmJava_nativeDestroyObject
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_henrywarhurst_facerecog_FisherSvmJava
 * Method:    nativeTrain
 * Signature: (JLjava/util/List;Ljava/util/List;)V
 */
JNIEXPORT void JNICALL Java_com_henrywarhurst_facerecog_FisherSvmJava_nativeTrain
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     com_henrywarhurst_facerecog_FisherSvmJava
 * Method:    nativePredict
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_henrywarhurst_facerecog_FisherSvmJava_nativePredict
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
