/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_henrywarhurst_facerecog_Hmm */

#ifndef _Included_com_henrywarhurst_facerecog_Hmm
#define _Included_com_henrywarhurst_facerecog_Hmm
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_henrywarhurst_facerecog_Hmm
 * Method:    nativeConstruct
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_henrywarhurst_facerecog_Hmm_nativeConstruct
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_henrywarhurst_facerecog_Hmm
 * Method:    nativeDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_henrywarhurst_facerecog_Hmm_nativeDestroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_henrywarhurst_facerecog_Hmm
 * Method:    getSequenceMode
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_com_henrywarhurst_facerecog_Hmm_getSequenceMode
  (JNIEnv *, jobject, jlong thiz, jintArray);

#ifdef __cplusplus
}
#endif
#endif
